export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h1>Navbar</h1>
          <ul>
            <li>Inicio</li>
            <li>Acerca de nosotros</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
